version: '3'

services:
  db:
    container_name: co2_db  # Nome do container do banco de dados
    image: postgres:latest
    environment:
      POSTGRES_DB: co2_emissions  # Nome do banco de dados
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgresql_data:/var/lib/postgresql/data
      - ./co2_emissions.sql:/docker-entrypoint-initdb.d/co2_emissions.sql  # Script inicial
      - ./files:/files  # Pasta para arquivos adicionais
    ports:
      - 55432:5432
    networks:
      - db

  pgadmin:
    container_name: co2_pgadmin  # Nome do container do PgAdmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: postgres
      PGADMIN_LISTEN_PORT: 5050
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - postgresql_bin:/usr/lib/postgresql
      - pgadmin_root_prefs:/root/.pgadmin
      - pgadmin_working_dir:/var/lib/pgadmin
      - ./files:/files
    ports:
      - 5050:5050
    networks:
      - db

networks:
  db:
    driver: bridge

volumes:
  pgadmin_root_prefs:
    driver: local
  pgadmin_working_dir:
    driver: local
  postgresql_data:
    driver: local
  postgresql_bin:
    driver: local
